### ISSUE TITLE
Couldn't extract archive kong-external-oauth: unrecognized filename extension

### ISSUE THREAD

**Issue by jdarling** [mogui/kong-external-oauth#2]
When trying to install external oauth with Lua 5.1 and latest rocks I'm getting the error "Couldn't extract archive kong-external-oauth: unrecognized filename extension"

Now I realize that this "typically" means that the extractor necessary isn't installed on the host, but I validated that I have unzip, tar, and gzip installed properly.  Not real sure what is wrong here.  Any thoughts?

Tail of the logs (only the important bits I hope):

```
os.execute: 	cd '/home/jdarling/luarocks-2.4.1' && test '-d' '/tmp/luarocks_external-oauth-1.0-3-bo42oU'
Results: 1
  1 (number): 0

os.execute: 	cd '/tmp/luarocks_external-oauth-1.0-3-bo42oU' && unzip -n '/tmp/luarocks_luarocks-rock-external-oauth-1.0-3-RTLCpz/external-oauth-1.0-3.src.rock'
Archive:  /tmp/luarocks_luarocks-rock-external-oauth-1.0-3-RTLCpz/external-oauth-1.0-3.src.rock
  inflating: external-oauth-1.0-3.rockspec  
  inflating: kong-external-oauth     
Results: 1
  1 (number): 0

os.execute: 	cd '/home/jdarling/luarocks-2.4.1' && test '-d' '/tmp/luarocks_external-oauth-1.0-3-bo42oU'
Results: 1
  1 (number): 0

os.execute: 	cd '/tmp/luarocks_external-oauth-1.0-3-bo42oU' && test '-e' 'external-oauth-1.0-3.rockspec'
Results: 1
  1 (number): 0

os.execute: 	cd '/tmp/luarocks_external-oauth-1.0-3-bo42oU' && test '-d' '/home/jdarling/.luarocks/lib/luarocks/rocks/external-oauth/1.0-3'
Results: 1
  1 (number): 256

os.execute: 	cd '/' && rm '-rf' '/tmp/luarocks_external-oauth-1.0-3-bo42oU'
Results: 1
  1 (number): 0

os.execute: 	cd '/' && rm '-rf' '/tmp/luarocks_luarocks-rock-external-oauth-1.0-3-RTLCpz'
Results: 1
  1 (number): 0
```

**Comment by mogui** [comment]
don't know, seems ok I can try to re upload it, since also it seems vanished from luarocks when I try to install it :O

**Comment by XVincentX** [comment]
I'm having the exact same issue here @mogui

**Comment by XVincentX** [comment]
@mogui For what is worth, I've resolved by manually installing the plugin from the sources.

```bash
git clone https://github.com/mogui/kong-external-oauth
cd kong-external-oauth && luarocks make
```

**Comment by mogui** [comment]
@XVincentX sorry for that, I'll try to understand what it's wrong with luarocks :(

**Comment by XVincentX** [comment]
Thanks @mogui ; I've also opened a PR - it would be great if you'd like to review it!

**Comment by mogui** [comment]
@XVincentX i'll look into that shortly,
Thanks!

**Comment by mogui** [comment]
can you try to install from luarocks now?
I'm still having problems, don't know if it's just me, 
it seems luarocks cli cannot find it, but it is present on the root manifest

**Comment by XVincentX** [comment]
I'm still having the same issue.
Also, it seems like you changed the package name.

![image](https://user-images.githubusercontent.com/1416224/28362095-7e2b9252-6c7b-11e7-96ab-1502b2770b2a.png)

**Comment by elasticroentgen** [comment]
Same problem still exists here. Tried it again right now. Also building from source seems to be broken.
```
sh-4.2# git clone https://github.com/mogui/kong-external-oauth                                                                       
Cloning into 'kong-external-oauth'...                                                                                                
xternal-oauth && luarocks makeremote: Counting objects: 67, done.                                                                    
remote: Compressing objects: 100% (33/33), done.                                                                                     
remote: Total 67 (delta 18), reused 29 (delta 8), pack-reused 26                                                                     
Unpacking objects: 100% (67/67), done.                                                                                               
sh-4.2# cd kong-external-oauth && luarocks make                                                                                      
                                                                                                                                     
Error: Inconsistency between rockspec filename (external-oauth-1.1-1.rockspec) and its contents (kongexternaloauth-1.1-1.rockspec).  
sh-4.2#
```

**Comment by XVincentX** [comment]
It's because the package name has been changed, therefore now there's an inconsistency.

It used to work from source.

**Comment by mogui** [comment]
Yep sorry the module name change was a test, fixed now.
so build from source should work.
Still getting the `No results matching error` though.
I've opened an issue on luarocks https://github.com/luarocks/luarocks/issues/720

**Comment by XVincentX** [comment]
Cool, thanks!
Keep us posted!

**Comment by mogui** [comment]
Last commit should have fixed everyhting also the fomrer `unrecognized filename extension`.
the source url must be specified as git:// ora an http to a tar.gz
Error messages weren't helping so much but now everything should be ok
`luarocks install external-oauth` should behave correctly
I close the issue but double check, I'll reopen if it's needed
Thanks

**Comment by XVincentX** [comment]
Unfortunately something is still wrong here :(

![image](https://user-images.githubusercontent.com/1416224/28387725-7e612106-6cd0-11e7-89db-4e7628997983.png)

**Comment by mogui** [comment]
something wrong you're trying to pull revision 1.1-2 while online on luarocks there is 1.1-5 try to clean luarocks cache

m0gui - Keep calm & code in C
---
pub 1024D/3BF6890C
Key fingerprint = CEDD 4512 3248 4C9C 2493 FE56 2E55 A884 3BF6 890C
server: pgp.mit.edu

**Comment by XVincentX** [comment]
`luarocks show external-oauth` is giving me this output:

![image](https://user-images.githubusercontent.com/1416224/28406280-282d47c8-6d30-11e7-9b21-55f4b7a102a5.png)


Latest version is missing!

**Comment by mogui** [comment]
It's something with your cache @XVincentX 

look https://luarocks.org/modules/mogui/external-oauth

**Comment by XVincentX** [comment]
It might be related to the required Lua version

https://github.com/luarocks/luarocks/issues/601

Kong is shipping with 5.1, so we should probably stick with that

**Comment by mogui** [comment]
requirements are stated as >= 5.1 it shouldn't be a problem i think

**Comment by XVincentX** [comment]
Unfortunately I still haven't been able to figure this out. For some reason I just get version till 1.1-2 when used in `kong` docker container.

I'm installing it from source and it's working correctly. I'll keep going in this way for now.

**Comment by videni** [comment]
@XVincentX , hi ,  I also have this problem , and  figure it out with this way [unrecognized filename extension when install a package](https://github.com/luarocks/luarocks/issues/826)
